const D=window.FDBS_DATA, main=document.querySelector('#main');
const norm=s=>(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const track=(event,params={})=>{if(localStorage.getItem('fdbs-consent')==='granted')window.gtag('event',event,params)};
const button=(label,href,ghost=false)=>`<a class="button${ghost?' ghost':''}" href="${href}">${label}</a>`;
const hero=(title,copy,eyebrow='Donează sânge')=>`<section class="page-hero"><div><span class="eyebrow">${eyebrow}</span><h1>${title}</h1><p>${copy}</p></div></section>`;
const wrap=(html,alt=false)=>`<section class="section${alt?' alt':''}"><div class="container">${html}</div></section>`;

function home(){return `<section class="hero"><div class="hero-inner"><span class="eyebrow">Fundația Donatorilor Benevoli de Sânge</span><h1 class="display">Donează sânge.<br>Poți salva o viață.</h1><p>Un gest care durează câteva minute poate însemna o nouă șansă pentru cineva.</p><div class="actions">${button('Vreau să donez','#/pot-sa-donez')}${button('Găsește un centru','#/centre',true)}</div></div></section>
${wrap(`<div class="quick-check"><div><span class="eyebrow">Verificare rapidă</span><h2>Pot să donez?</h2><p>Acestea sunt câteva dintre criteriile generale. Medicul de la triaj ia decizia finală.</p>${button('Verifică dacă poți dona','#/pot-sa-donez')}</div><div class="criteria"><div class="criterion"><b>18–60 ani</b><span>interval general de vârstă</span></div><div class="criterion"><b>50–130 kg</b><span>interval de greutate</span></div><div class="criterion"><b>Stare bună</b><span>de sănătate</span></div><div class="criterion"><b>Act valabil</b><span>de identitate</span></div></div></div>`,true)}
${wrap(`<div class="section-head"><div><span class="eyebrow">Simplu, în cinci pași</span><h2>Donarea, pe scurt</h2></div><a class="text-link" href="#/cum-donez">Vezi cum se desfășoară →</a></div><div class="process">${['Pregătește-te','Mergi la centru','Treci prin triaj','Donează','Odihnește-te'].map((x,i)=>`<div><span>0${i+1}</span><h3>${x}</h3></div>`).join('')}</div>`)}
${wrap(`<div class="map-preview"><div><span class="eyebrow">47 de locații</span><h2>Găsește centrul cel mai apropiat</h2><p>Folosește căutarea după oraș sau județ și deschide traseul direct în Google Maps.</p>${button('Caută un centru','#/centre')}</div><div class="map-mini map" id="home-map"></div></div>`)}
${wrap(`<div class="section-head"><div><span class="eyebrow">Întrebări reale</span><h2>Ai o întrebare despre donare?</h2></div></div><div class="search-box" style="max-width:760px"><input id="home-faq-search" placeholder="Caută: medicamente, tatuaj, menstruație, stomatolog…"><a class="button" href="#/faq">Caută</a></div>`,true)}
${wrap(`<div class="section-head"><div><span class="eyebrow">Acum la FDBS</span><h2>Lucrăm pentru donatori</h2></div></div><div class="grid-3" style="grid-template-columns:1fr 1fr"><article class="project-card"><span class="eyebrow">Proiect în desfășurare</span><h3>Actualizarea criteriilor de eligibilitate</h3><p>Excluderea donatorilor trebuie să se bazeze pe riscuri medicale reale și dovezi actuale.</p><a class="text-link" href="#/criterii">Vezi proiectul →</a></article><article class="project-card donorium-card"><span class="eyebrow">Proiect fondat de FDBS</span><h3>Donorium</h3><p><b>Peste 240.000 de utilizatori</b><br>O comunitate digitală care face donarea mai simplă.</p><a class="text-link" href="#/donorium">Descoperă proiectul →</a></article></div>`)}
${wrap(`<div class="section-head"><div><span class="eyebrow">Din 1996</span><h2>Alături de donatori.</h2></div><p>FDBS lucrează pentru ca mai mulți oameni să doneze sânge și pentru ca experiența donatorilor din România să fie mai bună.</p></div>${button('Citește povestea FDBS','#/istoric')}`,true)}`}

function eligibility(){return hero('Pot să donez?','Verifică principalele criterii înainte de a merge la centru. Aceste informații te ajută să te orientezi; decizia finală aparține medicului de la triaj.')+wrap(`<div class="criteria"><div class="criterion"><b>18–60 ani</b><span>vârsta generală</span></div><div class="criterion"><b>50–130 kg</b><span>greutatea acceptată</span></div><div class="criterion"><b>Fără alcool</b><span>în ultimele 48 de ore</span></div><div class="criterion"><b>Stare bună</b><span>de sănătate în ziua donării</span></div></div><div class="notice" style="margin-top:35px"><b>Ai o situație medicală specifică?</b><br>Caută în întrebările frecvente sau discută direct cu medicul de la triaj.</div><div class="actions">${button('Caută în întrebări','#/faq')}${button('Găsește un centru','#/centre',true)}</div>`)}
function how(){const steps=[['Cu 48 de ore înainte','Nu consuma alcool în cele 48 de ore înainte de donare.'],['Cu o zi înainte','Odihnește-te bine și bea suficiente lichide.'],['În dimineața donării','Nu veni nemâncat. Mănâncă ceva consistent, evită excesul de grăsimi și poartă haine care permit accesul ușor la braț.'],['Înregistrarea','Prezintă un act de identitate valabil și completează chestionarul donatorului.'],['Triajul','Răspunde sincer. Interviul medical și rezultatele analizelor sunt confidențiale.'],['Donarea','Se recoltează aproximativ 450 ml, în general în 7–10 minute, cu un kit steril de unică folosință.'],['După donare','Odihnește-te, hidratează-te și evită efortul fizic intens. Nu fuma o oră înainte și o oră după donare.']];return hero('Cum donez?','Donarea propriu-zisă durează doar câteva minute. Pregătește-te corect și acordă-ți puțin timp pentru refacere după.')+wrap(`<div class="steps">${steps.map((s,i)=>`<article class="step"><div class="step-number">${String(i+1).padStart(2,'0')}</div><div><h2>${s[0]}</h2><p>${s[1]}</p></div></article>`).join('')}</div><div class="notice"><b>Ți-e frică de ace sau știi că ai tendința să amețești?</b><br>Spune-i personalului medical. Este mai bine să știe de la început.</div><div class="actions">${button('Găsește un centru de donare','#/centre')}</div>`)}

function centresPage(){return hero('Unde pot dona?','Caută după oraș, județ sau denumirea centrului. Programul se poate modifica; verifică înainte de deplasare dacă ai dubii.')+wrap(`<div class="directory-layout"><div class="directory-list"><div class="directory-controls"><div class="search-box"><input id="centre-search" aria-label="Caută centru" placeholder="Caută oraș sau județ…"><button class="button" id="locate">Locația mea</button></div><small id="centre-count">${D.centres.length} locații</small></div><div id="centre-results"></div></div><div class="map" id="centre-map" aria-label="Harta centrelor de transfuzie"></div></div>`)}
const centreHoursLabel=c=>c.hours?`${['CTS Prahova','CTS Vrancea','CRTS Galați'].includes(c.name)?'':`${c.days}, `}${c.hours}`:c.days;
const citySlug=city=>norm(city).replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
function centreCard(c,d=''){return `<article class="centre-card" data-id="${c.id}" tabindex="0" style="position:relative;padding-right:88px"><h3>${c.name}</h3><p>${c.city}${d?` · <b>${d} km</b>`:''}</p><p>${c.address}</p><p><b>${centreHoursLabel(c)}</b></p><a class="text-link centre-details" href="#/centre/${citySlug(c.city)}">Detalii centru →</a><a class="navigate" target="_blank" rel="noopener" aria-label="Navighează cu Google Maps" title="Navighează cu Google Maps" href="https://www.google.com/maps/dir/?api=1&destination=${c.lat},${c.lng}" style="position:absolute;right:22px;top:50%;transform:translateY(-50%);display:block;width:48px;height:48px"><img src="assets/google-maps-icon.png" alt="" width="48" height="48" style="display:block;width:100%;height:100%;object-fit:contain"></a></article>`}
function cityCentrePage(slug){const centres=D.centres.filter(c=>citySlug(c.city)===slug),city=centres[0]?.city;if(!city)return hero('Centru negăsit','Revino la harta centrelor pentru a căuta o altă localitate.')+wrap(button('Vezi toate centrele','#/centre'));const plural=centres.length>1,map=city==='București'?`<section class="bucharest-map-section" aria-labelledby="bucharest-map-title"><span class="eyebrow">Cele 4 locații</span><h2 id="bucharest-map-title">Harta centrelor de donare din București</h2><p>Selectează un punct pentru a vedea centrul corespunzător.</p><div class="bucharest-map" id="bucharest-map" aria-label="Harta Bucureștiului cu cele patru centre de donare"></div></section>`:'';return `<nav class="breadcrumbs" aria-label="Navigare secundară"><a href="#/centre">Unde pot dona?</a><span aria-hidden="true">/</span><span>${city}</span></nav>${hero(`Donare de sânge în ${city}`,`${plural?`În ${city} sunt listate ${centres.length} centre unde poți dona sânge.`:`Aici găsești informațiile disponibile despre centrul de donare de sânge din ${city}.`} Programul se poate modifica; verifică înainte de deplasare dacă ai dubii.`,plural?'Centre de donare':'Centru de donare')}${wrap(`${map}<div class="city-centre-layout"><div><span class="eyebrow">${plural?'Centre în oraș':'Centrul din oraș'}</span><h2>${plural?`Unde poți dona în ${city}`:`Centrul de donare din ${city}`}</h2><div class="city-centre-list">${centres.map(c=>`<article class="city-centre-card" data-city-centre-id="${c.id}" tabindex="-1"><h3>${c.name}</h3><dl><div><dt>Adresă</dt><dd>${c.address}, ${c.city}</dd></div><div><dt>Program</dt><dd>${c.hours?centreHoursLabel(c):'Programul urmează să fie completat'}</dd></div></dl><a class="button small" target="_blank" rel="noopener" href="https://www.google.com/maps/dir/?api=1&destination=${c.lat},${c.lng}">Deschide în Google Maps</a></article>`).join('')}</div></div><aside class="city-donation-help"><span class="eyebrow">Înainte să pleci</span><h2>Pregătește-te pentru donare</h2><p>Verifică informațiile esențiale despre eligibilitate și pașii donării.</p><a class="text-link" href="#/pot-sa-donez">Pot să donez? →</a><a class="text-link" href="#/cum-donez">Cum donez? →</a><a class="text-link" href="#/faq">Întrebări frecvente →</a></aside></div><div class="notice city-centre-notice"><b>Informațiile despre program se pot modifica.</b><br>Dacă ai dubii, verifică programul înainte de deplasare.</div><p class="back-to-directory"><a class="text-link" href="#/centre">← Vezi harta tuturor centrelor de donare</a></p>`)}`}
function initBucharestMap(){const map=document.getElementById('bucharest-map'),centres=D.centres.filter(c=>c.city==='București'),data=window.BUCHAREST_MAP_DATA;if(!map||!data)return;const [minLng,minLat,maxLng,maxLat]=data.bbox,point=({lng,lat})=>({x:(lng-minLng)/(maxLng-minLng)*100,y:(maxLat-lat)/(maxLat-minLat)*64}),roads=[['Splaiul Independenței',[[25.96,44.447],[26.03,44.440],[26.08,44.429],[26.14,44.410],[26.20,44.398]]],['Bd. Iuliu Maniu',[[25.96,44.434],[26.01,44.434],[26.06,44.435],[26.08,44.433]]],['Calea Victoriei',[[26.085,44.426],[26.088,44.442],[26.091,44.459]]],['Magheru–Brătianu',[[26.098,44.462],[26.101,44.446],[26.103,44.425]]],['Kiseleff–Aviatorilor',[[26.071,44.510],[26.080,44.480],[26.089,44.458]]],['Ștefan cel Mare–Mihai Bravu',[[26.097,44.458],[26.130,44.451],[26.140,44.421],[26.139,44.387]]],['Bd. Unirii',[[26.083,44.427],[26.115,44.426],[26.161,44.424]]],['Calea Plevnei',[[26.020,44.449],[26.060,44.443],[26.090,44.438]]]],roadPaths=roads.map(([name,coords])=>`<path class="city-road" d="M${coords.map(p=>{const q=point({lng:p[0],lat:p[1]});return `${q.x.toFixed(2)} ${q.y.toFixed(2)}`}).join(' L')}"><title>${name}</title></path>`).join(''),sectors=data.sectors.map(s=>`<path class="city-sector sector-${s.id}" d="${s.path}"><title>Sectorul ${s.id}</title></path>`).join(''),labels=[[1,26.035,44.49],[2,26.145,44.485],[3,26.175,44.43],[4,26.11,44.375],[5,26.025,44.39],[6,25.985,44.455]].map(([n,lng,lat])=>{const p=point({lng,lat});return `<text class="sector-label" x="${p.x}" y="${p.y}">S${n}</text>`}).join('');map.innerHTML=`<svg class="bucharest-map-lines" viewBox="0 0 100 64" preserveAspectRatio="none" role="img" aria-label="Conturul Bucureștiului, limitele sectoarelor și arterele principale">${sectors}${roadPaths}${labels}</svg>`;centres.forEach((c,i)=>{const p=point(c),m=document.createElement('button');m.className='bucharest-marker';m.style=`left:${p.x}%;top:${p.y/64*100}%`;m.dataset.cityCentreId=c.id;m.setAttribute('aria-label',`${c.name}, ${c.address}`);m.innerHTML=`<span>${i+1}</span>`;m.onclick=()=>{map.querySelectorAll('.active').forEach(x=>x.classList.remove('active'));m.classList.add('active');const card=document.querySelector(`[data-city-centre-id="${c.id}"]`);card?.focus({preventScroll:true});card?.scrollIntoView({behavior:'smooth',block:'start'})};map.append(m)})}
const romaniaBoundary=[[22.710531,47.882194],[23.142236,48.096341],[23.760958,47.985598],[24.402056,47.981878],[24.866317,47.737526],[25.207743,47.891056],[25.945941,47.987149],[26.19745,48.220881],[26.619337,48.220726],[26.924176,48.123264],[27.233873,47.826771],[27.551166,47.405117],[28.12803,46.810476],[28.160018,46.371563],[28.054443,45.944586],[28.233554,45.488283],[28.679779,45.304031],[29.149725,45.464925],[29.603289,45.293308],[29.626543,45.035391],[29.141612,44.82021],[28.837858,44.913874],[28.558081,43.707462],[27.970107,43.812468],[27.2424,44.175986],[26.065159,43.943494],[25.569272,43.688445],[24.100679,43.741051],[23.332302,43.897011],[22.944832,43.823785],[22.65715,44.234923],[22.474008,44.409228],[22.705726,44.578003],[22.459022,44.702517],[22.145088,44.478422],[21.562023,44.768947],[21.483526,45.18117],[20.874313,45.416375],[20.762175,45.734573],[20.220192,46.127469],[21.021952,46.316088],[21.626515,46.994238],[22.099768,47.672439],[22.710531,47.882194]];
const mapPoint=([lng,lat])=>[(lng-20.5)/(29.8-20.5)*88+6,(48.3-lat)/(48.3-43.4)*78+10];
function mapRingPath(ring){return ring.map((point,i)=>`${i?'L':'M'}${mapPoint(point).map(n=>n.toFixed(2)).join(' ')}`).join(' ')+' Z'}
function countyMapPaths(){return (window.ROMANIA_COUNTIES||[]).map(county=>`<path class="county-shape" data-county="${county.name}" d="${county.polygons.map(polygon=>polygon.map(mapRingPath).join(' ')).join(' ')}"><title>${county.name}</title></path>`).join('')}
function renderMap(list,targetId='centre-map'){const map=document.getElementById(targetId);if(!map)return;const outline=romaniaBoundary.map((point,i)=>`${i?'L':'M'}${mapPoint(point).map(n=>n.toFixed(2)).join(' ')}`).join(' ')+' Z';const counties=countyMapPaths();map.innerHTML=`<svg class="country-outline" viewBox="0 0 100 100" preserveAspectRatio="none" role="img" aria-label="Harta României cu limitele județelor">${counties||`<path class="country-fill" d="${outline}"/>`}</svg>`;const bucharest=list.filter(c=>c.city==='București'),locations=list.filter(c=>c.city!=='București');if(bucharest.length>1){const cluster={lng:bucharest.reduce((s,c)=>s+c.lng,0)/bucharest.length,lat:bucharest.reduce((s,c)=>s+c.lat,0)/bucharest.length};let [x,y]=mapPoint([cluster.lng,cluster.lat]),m=document.createElement('button');m.className='marker marker-cluster';m.style=`left:${x}%;top:${y}%`;m.textContent=bucharest.length;m.title=`${bucharest.length} centre de donare în București`;m.setAttribute('aria-label',m.title);m.onclick=()=>showCentreGroupPopover(bucharest,cluster,true);m.onmouseenter=()=>showCentreGroupPopover(bucharest,cluster,false);m.onmouseleave=()=>map.querySelector('.map-popover.hover')?.remove();m.onfocus=()=>showCentreGroupPopover(bucharest,cluster,false);m.onblur=()=>map.querySelector('.map-popover.hover')?.remove();map.append(m)}locations.forEach(c=>{let [x,y]=mapPoint([c.lng,c.lat]);let m=document.createElement('button');m.className='marker';m.style=`left:${x}%;top:${y}%`;m.dataset.id=c.id;m.title=`${c.name}, ${c.city}`;m.setAttribute('aria-label',m.title);m.onclick=()=>selectCentre(c.id);m.onmouseenter=()=>showCentrePopover(c,false);m.onmouseleave=()=>map.querySelector('.map-popover.hover')?.remove();m.onfocus=()=>showCentrePopover(c,false);m.onblur=()=>map.querySelector('.map-popover.hover')?.remove();map.append(m)})}
const centreAlphabeticalKey=centre=>centre.name.replace(/^CR?TS\s+/i,'').trim();
const centresBucharestFirst=centres=>[...centres].sort((a,b)=>{const bucharestOrder=(b.city==='București')-(a.city==='București');return bucharestOrder||centreAlphabeticalKey(a).localeCompare(centreAlphabeticalKey(b),'ro',{sensitivity:'base'})});
function scrollCentreCardToTop(card){const scroller=card?.closest('.directory-list');if(!scroller)return;const controls=scroller.querySelector('.directory-controls'),target=scroller.scrollTop+card.getBoundingClientRect().top-scroller.getBoundingClientRect().top-(controls?.offsetHeight||0);scroller.scrollTo({top:Math.max(0,target),behavior:'smooth'})}
function focusBucharestCentres(){sessionStorage.setItem('fdbs-focus-bucharest','1');if(currentRoutePath()!=='/centre'){navigateToRoute('/centre');return}const input=document.getElementById('centre-search');if(!input)return;sessionStorage.removeItem('fdbs-focus-bucharest');input.value='București';input.dispatchEvent(new Event('input'));requestAnimationFrame(()=>{const card=document.querySelector('.centre-card');card?.focus({preventScroll:true});scrollCentreCardToTop(card)})}
function initCentres(){let list=centresBucharestFirst(D.centres),results=document.getElementById('centre-results'),input=document.getElementById('centre-search');const draw=()=>{results.innerHTML=list.map(c=>centreCard(c,c.distance)).join('');document.getElementById('centre-count').textContent=`${list.length} ${list.length===1?'locație':'locații'}`;renderMap(list);bindCards()};const bindCards=()=>document.querySelectorAll('.centre-card').forEach(card=>{card.onclick=e=>{if(!e.target.closest('.navigate'))selectCentre(+card.dataset.id)};card.onkeydown=e=>{if(e.key==='Enter')selectCentre(+card.dataset.id)}});input.oninput=()=>{let q=norm(input.value);list=centresBucharestFirst(D.centres.filter(c=>norm(`${c.name} ${c.city} ${c.county}`).includes(q)));draw();track('centre_search',{search_term:input.value,result_count:list.length})};document.getElementById('locate').onclick=()=>navigator.geolocation?navigator.geolocation.getCurrentPosition(pos=>{const la=pos.coords.latitude,lo=pos.coords.longitude;list=D.centres.map(c=>({...c,distance:(111*Math.sqrt((c.lat-la)**2+((c.lng-lo)*Math.cos(la*Math.PI/180))**2)).toFixed(1)})).sort((a,b)=>a.distance-b.distance);draw();track('use_my_location')},()=>alert('Locația nu a putut fi accesată. Poți căuta în continuare după oraș sau județ.')):alert('Browserul nu oferă acces la locație.');draw();if(sessionStorage.getItem('fdbs-focus-bucharest'))focusBucharestCentres()}
function showCentrePopover(c,persistent=true){const map=document.getElementById('centre-map')||document.getElementById('home-map');if(!map)return;map.querySelectorAll('.map-popover').forEach(p=>p.remove());const [rawX,y]=mapPoint([c.lng,c.lat]),x=Math.max(18,Math.min(82,rawX));const p=document.createElement('div');p.className=`map-popover${persistent?'':' hover'}${y<31?' below':''}`;p.style.left=`${x}%`;p.style.top=`${y}%`;p.innerHTML=`<b>${c.name}</b><small>${c.address}, ${c.city}<br>${c.hours?centreHoursLabel(c):'Programul urmează să fie completat'}</small>${persistent?`<a class="text-link" target="_blank" rel="noopener" href="https://www.google.com/maps/dir/?api=1&destination=${c.lat},${c.lng}">Navighează →</a>`:''}`;map.append(p)}
function showCentreGroupPopover(centres,position,persistent=true){const map=document.getElementById('centre-map')||document.getElementById('home-map');if(!map)return;map.querySelectorAll('.map-popover').forEach(p=>p.remove());const [rawX,y]=mapPoint([position.lng,position.lat]),x=Math.max(22,Math.min(78,rawX)),p=document.createElement('div');p.className=`map-popover map-popover-group${persistent?'':' hover'}${y<31?' below':''}`;p.style.left=`${x}%`;p.style.top=`${y}%`;p.innerHTML=`<b>${centres.length} centre în București</b><small>${centres.map(c=>c.name).join('<br>')}</small>${persistent?'<a class="text-link" href="#/centre" onclick="event.preventDefault();focusBucharestCentres()">Vezi centrele →</a>':''}`;map.append(p)}
function selectCentre(id){const c=D.centres.find(x=>x.id===+id),map=document.getElementById('centre-map');if(!c||!map)return;document.querySelectorAll('.active').forEach(x=>x.classList.remove('active'));document.querySelectorAll(`[data-id="${id}"]`).forEach(x=>x.classList.add('active'));scrollCentreCardToTop(document.querySelector(`.centre-card[data-id="${id}"]`));showCentrePopover(c,true);track('centre_marker_open',{centre:c.name,city:c.city})}

function faqPage(){let cats=[...new Set(D.faqs.map(f=>f.category))];return hero('Întrebări frecvente','Ai o întrebare despre donarea de sânge? Caută după cuvintele pe care le-ai folosi în mod obișnuit.')+wrap(`<div class="faq-tools"><div class="search-box"><input id="faq-search" placeholder="Caută: medicamente, tatuaj, cafea, analize…"></div><div class="filter-row"><button class="chip active" data-cat="">Toate</button>${cats.map(c=>`<button class="chip" data-cat="${c}">${c}</button>`).join('')}</div></div><div class="faq-list" id="faq-list"></div><div class="notice" style="margin-top:50px"><b>Nu ai găsit răspunsul?</b><br>Scrie-ne. Decizia finală privind acceptarea la donare aparține medicului de la centrul de transfuzie.</div>`)}
function initFaq(){let q='',cat='',shown=15;const draw=()=>{const list=document.getElementById('faq-list'),f=D.faqs.filter(x=>(!cat||x.category===cat)&&norm(`${x.question} ${x.answer} ${x.keywords}`).includes(norm(q))),visible=f.slice(0,shown);list.innerHTML=f.length?visible.map(x=>`<article class="faq-item"><button aria-expanded="false">${x.question}<span>＋</span></button><div class="faq-answer"><span class="eyebrow">${x.category}</span><p>${x.answer}</p>${x.related_page?`<a class="button ghost small" href="${x.related_page}">Vezi mai mult</a>`:''}</div></article>`).join('')+(f.length>shown?`<div class="faq-more"><button class="button" type="button">Vezi mai multe</button><small>${f.length-shown} întrebări rămase</small></div>`:''):`<div class="notice"><b>Nu am găsit un răspuns.</b><br>Încearcă o formulare mai scurtă sau scrie-ne întrebarea.</div>`;list.querySelectorAll('.faq-item button').forEach(b=>b.onclick=()=>{b.parentElement.classList.toggle('open');b.setAttribute('aria-expanded',b.parentElement.classList.contains('open'))});const more=list.querySelector('.faq-more button');if(more)more.onclick=()=>{shown+=15;draw()}};document.getElementById('faq-search').oninput=e=>{q=e.target.value;shown=15;draw();track('faq_search',{search_term:q})};document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{document.querySelector('.chip.active').classList.remove('active');b.classList.add('active');cat=b.dataset.cat;shown=15;draw()});draw()}

function projects(){return hero('Acum la FDBS','Două proiecte consistente, construite pentru donatori și pentru un sistem mai bun.')+wrap(`<div class="grid-3" style="grid-template-columns:1fr 1fr"><article class="project-card"><h3>Actualizare a criteriilor de eligibilitate a donatorilor în România</h3><p>Lucrăm pentru criterii bazate pe riscuri medicale reale și dovezi științifice actuale.</p><a class="text-link" href="#/criterii">Vezi proiectul →</a></article><article class="project-card donorium-card"><h3>Donorium</h3><p>FDBS este unul dintre fondatorii platformei cu peste 240.000 de utilizatori.</p><a class="text-link" href="#/donorium">Descoperă proiectul →</a></article></div>`)}
function criteriaProject(){return hero('Actualizarea criteriilor de eligibilitate','Lucrăm pentru actualizarea criteriilor din România, astfel încât excluderea de la donare să se bazeze pe riscuri medicale reale și dovezi științifice actuale.','Acum la FDBS')+wrap(`<div class="steps"><article class="step"><div class="step-number">2025</div><div><h2>Prezentarea analizei comparative</h2><p>Analiza criteriilor din România, Italia și Regatul Unit a fost prezentată la Congresul Național al Societății Române de Hematologie 2025.</p></div></article></div><div class="notice"><b>Analiză comparativă: România, Italia și Regatul Unit</b><br><a class="button" style="margin-top:16px" href="assets/analiza-comparativa-criterii-eligibilitate-ro-it-uk.pdf" download>Descarcă PDF</a></div>`)}
function donorium(){return hero('Donorium','De la o idee la o comunitate de peste 240.000 de utilizatori. FDBS este unul dintre fondatorii platformei create pentru a simplifica legătura dintre donatori și centre.','Acum la FDBS')+`<figure class="donorium-hero"><img src="assets/lansare-donorium-fondatori-platforma-donare-sange-romania.jpg" alt="Echipa Donorium la evenimentul de lansare al platformei pentru donatorii de sânge."><figcaption>Echipa Donorium la evenimentul de lansare al platformei.</figcaption></figure>`+wrap(`<div class="map-preview"><div><span class="eyebrow">Peste</span><h2>240.000</h2><p>de utilizatori fac parte din comunitatea Donorium.</p><a class="button light" href="https://donorium.ro" target="_blank" rel="noopener">Vizitează Donorium</a></div><div><h2>O comunitate pentru donatori</h2><p>Donorium a fost creat pentru a face mai simplă legătura dintre donatori și centrele de transfuzie sanguină din România.</p></div></div>`)}
function galleryWallImages(){return Object.entries(window.FDBS_IMAGE_POOLS?.gallery||{}).flatMap(([period,value])=>{const images=Array.isArray(value)?value:value?[value]:[];return images.filter(image=>image.active!==false).map(image=>({...image,period}))})}
function galleryImageLabel(image){const key=(image.alt||'').trim().replace(/(tonitza)\d+$/,'$1'),labels={'conferinta de presa cts bucuresti':'Conferință de presă la CTS București','expozitie desene elevi tonitza':'Expoziția elevilor de la Liceul Tonitza','masa rotunda medici 2004':'Masă rotundă cu medici','carticica fotbal donare':'Fotbal și donare de sânge','carticica micii fotbalisti marii donatori':'Micii fotbaliști, marii donatori','prezentare liceu':'Prezentare pentru elevi','seminar profesori 2007':'Seminar pentru profesori','tabara donatori muntele rosu 2005':'Tabăra donatorilor, Muntele Roșu'};return labels[key]||key.replace(/[-_]+/g,' ').replace(/\b\w/g,c=>c.toUpperCase())||'Imagine din arhiva FDBS'}
function gallery(){const images=galleryWallImages(),periods=[...new Set(images.map(image=>image.period))];return `<section class="gallery-wall-hero"><div><span class="eyebrow">Arhiva fotografică FDBS</span><h1>Oameni, gesturi și momente.</h1></div><p>Imagini din istoria FDBS, campanii, întâlniri și proiecte dedicate donării benevole de sânge.</p></section><section class="gallery-wall-controls" aria-label="Filtre galerie"><div class="gallery-wall-filters"><button class="gallery-filter active" data-gallery-period="toate">Toate</button>${periods.map(period=>`<button class="gallery-filter" data-gallery-period="${period}">${period}</button>`).join('')}</div><span class="gallery-wall-count">${images.length} fotografii</span></section><section class="gallery-wall" aria-live="polite">${images.map((image,index)=>`<button class="gallery-wall-photo" data-period="${image.period}" data-src="${image.src}" data-label="${galleryImageLabel(image)}" aria-label="Mărește: ${galleryImageLabel(image)}"><img src="${image.src}" alt="${galleryImageLabel(image)}" loading="${index<8?'eager':'lazy'}"><span class="gallery-wall-caption"><b>${galleryImageLabel(image)}</b><span>${image.period}</span></span></button>`).join('')}</section><dialog class="gallery-viewer"><div><button class="gallery-viewer-close" aria-label="Închide">×</button><img alt=""><p></p></div></dialog>`}
function initGalleryWall(){const wall=document.querySelector('.gallery-wall'),viewer=document.querySelector('.gallery-viewer'),count=document.querySelector('.gallery-wall-count');if(!wall||!viewer)return;const photos=[...wall.querySelectorAll('.gallery-wall-photo')];document.querySelectorAll('.gallery-filter').forEach(filter=>filter.onclick=()=>{document.querySelectorAll('.gallery-filter').forEach(button=>button.classList.remove('active'));filter.classList.add('active');const period=filter.dataset.galleryPeriod;let visible=0;photos.forEach(photo=>{const show=period==='toate'||photo.dataset.period===period;photo.hidden=!show;if(show)visible++});count.textContent=`${visible} fotografii`});photos.forEach(photo=>photo.onclick=()=>{const image=viewer.querySelector('img');image.src=photo.dataset.src;image.alt=photo.dataset.label;viewer.querySelector('p').innerHTML=`<b>${photo.dataset.label}</b><span>${photo.dataset.period}</span>`;viewer.showModal()});viewer.querySelector('.gallery-viewer-close').onclick=()=>viewer.close();viewer.onclick=event=>{if(event.target===viewer)viewer.close()}}
function dailyGallery(){const day=Math.floor(Date.now()/86400000);return D.gallery.map((e,i)=>Object.assign([...e],{seed:(day*31+i*7)%12}))}
function galleryPoolKey(period){return period.replace('–','-').replace('2020-prezent','2020-prezent')}
function dailyGalleryImages(period,eraIndex){const pool=(window.FDBS_IMAGE_POOLS?.gallery?.[galleryPoolKey(period)]||[]).filter(image=>image.active!==false);if(!pool.length)return[];const day=Math.floor(Date.now()/86400000),start=(day+eraIndex*3)%pool.length;return Array.from({length:Math.min(3,pool.length)},(_,i)=>pool[(start+i)%pool.length])}
function applyDailyHomeHero(){const hero=document.querySelector('.hero'),pool=(D.homeHeroImages||[]).filter(image=>image.active!==false);if(!hero||!pool.length)return;const now=new Date(),dayKey=Number(`${now.getFullYear()}${String(now.getMonth()+1).padStart(2,'0')}${String(now.getDate()).padStart(2,'0')}`),image=pool[dayKey%pool.length];hero.style.setProperty('--hero-image',`url("${image.src}")`);hero.style.setProperty('--hero-position',image.position||'center');hero.style.setProperty('--hero-mobile-position',image.mobilePosition||image.position||'center');hero.setAttribute('role','img');hero.setAttribute('aria-label',image.alt||'Donare de sânge')}
function aboutPage(){return hero('Din 1996, alături de donatori.','Fundația Donatorilor Benevoli de Sânge lucrează pentru ca mai mulți oameni să doneze și pentru ca experiența lor să fie mai bună.','Despre noi')+wrap(`<div class="section-head"><div><h2>Povestea FDBS</h2></div><p>De la primele campanii la proiecte digitale și la demersuri pentru actualizarea criteriilor de eligibilitate.</p></div>${button('Explorează arhiva','#/galerie')}`)}
function involve(){return hero('Implică-te','Poți ajuta printr-o colectă organizată cu centrul local, prin voluntariat sau prin sprijin financiar.')+wrap(`<div class="grid-3"><article class="card"><span class="num">01</span><h3>Organizează o donare</h3><p>Discută cu centrul de transfuzie din orașul tău despre o colectă pentru organizația sau comunitatea ta.</p></article><article class="card"><span class="num">02</span><h3>Devino voluntar</h3><p>Implică-te în activitatea și campaniile FDBS.</p></article><article class="card"><span class="num">03</span><h3>Sprijină-ne financiar</h3><p>Prin 3,5%, sponsorizare sau donație directă.</p></article></div>`)}
function privacy(){return hero('Confidențialitate și cookies','Colectăm doar datele necesare funcționării site-ului. Analiza anonimă a utilizării este activată numai cu acordul tău.')+wrap(`<h2>Preferințele tale</h2><p>Poți modifica oricând alegerea folosind „Preferințe cookies” din subsol. Căutările FAQ fără rezultat și interacțiunile cu centrele sunt trimise către instrumentul de analiză numai după consimțământ și nu includ date medicale ori coordonatele exacte ale utilizatorului.</p>`)}

const routes={'/':home,'/pot-sa-donez':eligibility,'/cum-donez':how,'/centre':centresPage,'/faq':faqPage,'/acum':projects,'/criterii':criteriaProject,'/donorium':donorium,'/galerie':gallery,'/istoric':aboutPage,'/implica-te':involve,'/confidentialitate':privacy};
const publicRoutes={'/':'/','/pot-sa-donez':'/pot-sa-donez/','/cum-donez':'/cum-donez/','/centre':'/centre/','/faq':'/intrebari-frecvente/','/acum':'/proiecte-actuale/','/criterii':'/criterii-eligibilitate/','/donorium':'/donorium/','/galerie':'/galerie/','/istoric':'/despre-noi/','/implica-te':'/implica-te/','/confidentialitate':'/confidentialitate/'};
function routeUrl(path){const city=path.match(/^\/centre\/([^/]+)$/),url=city?`/centre/${city[1]}/`:publicRoutes[path]||'/';return location.protocol==='file:'?`${window.FDBS_ROOT_PREFIX||''}index.html#${path}`:url}
function routeFromPublicPath(pathname){const clean=decodeURI(pathname).replace(/\/index\.html$/,'/').replace(/\/+$/,'/')||'/';const city=clean.match(/\/centre\/([^/]+)\/$/);if(city)return `/centre/${city[1]}`;const entry=Object.entries(publicRoutes).find(([,url])=>url==='/'?clean==='/':clean.endsWith(url));return entry?.[0]||'/'}
function currentRoutePath(){return location.hash.startsWith('#/')?location.hash.slice(1).split('?')[0]:routeFromPublicPath(location.pathname)}
function navigateToRoute(path){const url=routeUrl(path);if(location.protocol==='file:'){location.href=url;return}window.history.pushState({},'',url);route()}
function rewriteInternalLinks(root=document){root.querySelectorAll('a[href^="#/"]').forEach(a=>{const raw=a.getAttribute('href').slice(1),[path,query]=raw.split('?');a.href=routeUrl(path)+(query?`?${query}`:'')})}
function updateCanonical(path){let canonical=document.querySelector('link[rel="canonical"]');if(!canonical){canonical=document.createElement('link');canonical.rel='canonical';document.head.append(canonical)}canonical.href=`https://doneazasange.ro${routeUrl(path)}`}
function route(){let path=currentRoutePath(),cityMatch=path.match(/^\/centre\/([^/]+)$/),fn=cityMatch?()=>cityCentrePage(cityMatch[1]):routes[path]||home;if(location.protocol!=='file:'&&location.hash.startsWith('#/'))window.history.replaceState({},'',routeUrl(path));main.innerHTML=fn();document.querySelector('#footer-cta').hidden=path==='/centre';window.scrollTo(0,0);document.title=`${path==='/'?'FDBS — Donează sânge':main.querySelector('h1')?.textContent+' — FDBS'}`;updateCanonical(path);rewriteInternalLinks(document);document.querySelector('.site-header').classList.remove('open');document.querySelector('.menu-toggle').setAttribute('aria-expanded','false');if(path==='/centre')initCentres();if(cityMatch?.[1]==='bucuresti')initBucharestMap();if(path==='/faq')initFaq();if(path==='/galerie')initGalleryWall();if(path==='/'){applyDailyHomeHero();renderMap(D.centres,'home-map');const input=document.getElementById('home-faq-search');input.onkeydown=e=>{if(e.key==='Enter')location.href=`${routeUrl('/faq')}?q=${encodeURIComponent(input.value)}`}}rewriteInternalLinks(main);track('page_view',{page_path:path})}
function initBucharestMap(){const map=document.getElementById('bucharest-map'),centres=D.centres.filter(c=>c.city==='București'),data=window.BUCHAREST_MAP_DATA;if(!map||!data)return;const [minLng,minLat,maxLng,maxLat]=data.bbox,point=({lng,lat})=>({x:4+(lng-minLng)/(maxLng-minLng)*92,y:15+(maxLat-lat)/(maxLat-minLat)*70}),sectors=data.sectors.map(s=>`<path class="city-sector sector-${s.id}" d="${s.path}"><title>Sectorul ${s.id}</title></path>`).join(''),labels=[[1,26.035,44.49],[2,26.145,44.485],[3,26.175,44.43],[4,26.11,44.375],[5,26.025,44.39],[6,25.985,44.455]].map(([n,lng,lat])=>{const x=(lng-minLng)/(maxLng-minLng)*100,y=(maxLat-lat)/(maxLat-minLat)*64;return `<text class="sector-label" x="${x}" y="${y}">S${n}</text>`}).join('');map.innerHTML=`<img class="bucharest-map-image" src="assets/harta-bucuresti-detaliata.png" alt="Hartă detaliată a Bucureștiului cu străzi, spații verzi și lacuri"><svg class="bucharest-sector-overlay" viewBox="0 0 100 64" preserveAspectRatio="none" aria-label="Limitele celor șase sectoare ale Bucureștiului">${sectors}${labels}</svg>`;centres.forEach((c,i)=>{const p=point(c),m=document.createElement('button');m.className='bucharest-marker';m.style=`left:${p.x}%;top:${p.y}%`;m.dataset.cityCentreId=c.id;m.setAttribute('aria-label',`${c.name}, ${c.address}`);m.innerHTML=`<span>${i+1}</span>`;m.onclick=()=>{map.querySelectorAll('.active').forEach(x=>x.classList.remove('active'));m.classList.add('active');const card=document.querySelector(`[data-city-centre-id="${c.id}"]`);card?.focus({preventScroll:true});card?.scrollIntoView({behavior:'smooth',block:'start'})};map.append(m)})}
const initBucharestMapBase=initBucharestMap;initBucharestMap=function(){initBucharestMapBase();const map=document.getElementById('bucharest-map'),zoom=1.42;if(!map)return;map.querySelector('.bucharest-map-image')?.classList.add('bucharest-map-zoom');map.querySelector('.bucharest-sector-overlay')?.classList.add('bucharest-map-zoom');map.querySelectorAll('.bucharest-marker').forEach(marker=>{marker.style.left=`${50+(parseFloat(marker.style.left)-50)*zoom}%`;marker.style.top=`${50+(parseFloat(marker.style.top)-50)*zoom}%`});map.querySelectorAll('.sector-label').forEach(label=>{const x=parseFloat(label.getAttribute('x')),y=parseFloat(label.getAttribute('y'));label.setAttribute('x',50+(x-50)*.7);label.setAttribute('y',32+(y-32)*.7)})};
const initBucharestMapWithZoom=initBucharestMap;initBucharestMap=function(){initBucharestMapWithZoom();const centres=D.centres.filter(c=>c.city==='București');document.querySelectorAll('.bucharest-marker').forEach((marker,i)=>{marker.dataset.name=centres[i]?.name||'';marker.title=centres[i]?.name||''})};
function showBucharestCentrePopover(c,marker){const map=document.getElementById('bucharest-map');if(!map)return;map.querySelectorAll('.map-popover').forEach(p=>p.remove());const top=parseFloat(marker.style.top),p=document.createElement('div');p.className=`map-popover hover${top<31?' below':''}`;p.style.left=marker.style.left;p.style.top=marker.style.top;p.innerHTML=`<b>${c.name}</b><small>${c.address}, ${c.city}<br>${c.hours?centreHoursLabel(c):'Programul urmează să fie completat'}</small>`;map.append(p)}
const initBucharestMapWithNames=initBucharestMap;initBucharestMap=function(){initBucharestMapWithNames();const map=document.getElementById('bucharest-map'),centres=D.centres.filter(c=>c.city==='București');map?.querySelectorAll('.bucharest-marker').forEach((marker,i)=>{const c=centres[i];marker.onmouseenter=()=>showBucharestCentrePopover(c,marker);marker.onmouseleave=()=>map.querySelector('.map-popover.hover')?.remove();marker.onfocus=()=>showBucharestCentrePopover(c,marker);marker.onblur=()=>map.querySelector('.map-popover.hover')?.remove()})};
document.querySelector('.menu-toggle').onclick=e=>{const h=document.querySelector('.site-header');h.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',h.classList.contains('open'))};
document.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-lang]').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(b.dataset.lang!=='ro')alert(b.dataset.lang==='hu'?'A magyar nyelvi struktúra este pregătită în CMS; conținutul aprobat este publicat momentan în română.':'The English language structure is ready in the CMS; approved content is currently published in Romanian.')});
const banner=document.querySelector('.cookie-banner');if(!localStorage.getItem('fdbs-consent'))banner.hidden=false;document.querySelectorAll('[data-consent]').forEach(b=>b.onclick=()=>{localStorage.setItem('fdbs-consent',b.dataset.consent);banner.hidden=true});document.getElementById('cookie-settings').onclick=()=>banner.hidden=false;
const replaceCurrentProjectsLabel=render=>()=>render().replaceAll('Acum la FDBS','Proiecte actuale');
home=replaceCurrentProjectsLabel(home);projects=replaceCurrentProjectsLabel(projects);criteriaProject=replaceCurrentProjectsLabel(criteriaProject);donorium=replaceCurrentProjectsLabel(donorium);routes['/']=home;routes['/acum']=projects;routes['/criterii']=criteriaProject;routes['/donorium']=donorium;
const cityCentrePageWithCentreTerminology=cityCentrePage;
cityCentrePage=slug=>slug==='bucuresti'?cityCentrePageWithCentreTerminology(slug)
  .replaceAll('Harta centrelor de donare','Harta punctelor de colectă')
  .replaceAll('cele patru centre de donare','cele patru puncte de colectă')
  .replaceAll('centrul corespunzător','punctul de colectă corespunzător')
  .replaceAll(' centre unde poți dona sânge',' puncte unde poți dona sânge')
  .replaceAll('centrul de donare de sânge','punctul de colectă de sânge')
  .replaceAll('Centre de donare','Puncte de colectă')
  .replaceAll('Centru de donare','Punct de colectă')
  .replaceAll('Centre în oraș','Puncte în oraș')
  .replaceAll('Centrul din oraș','Punctul din oraș')
  .replaceAll('Centrul de donare din','Punctul de colectă din')
  .replaceAll('tuturor centrelor de donare','tuturor punctelor de colectă')
  .replaceAll('Centru negăsit','Punct negăsit')
  .replaceAll('harta centrelor','harta punctelor')
  .replaceAll('toate centrele','toate punctele'):cityCentrePageWithCentreTerminology(slug);
const cityCentrePageWithRedundantHeading=cityCentrePage;
function addCityScheduleVerification(slug){let html=cityCentrePageWithRedundantHeading(slug).replace(/<span class="eyebrow">(?:Centre|Centrul|Puncte|Punctul)[^<]*<\/span><h2>[^<]*<\/h2>(?=<div class="city-centre-list">)/,'');D.centres.filter(c=>citySlug(c.city)===slug&&c.hours&&!c.hours.includes('?')).forEach(c=>{const row=`<div><dt>Program</dt><dd>${centreHoursLabel(c)}</dd></div>`;html=html.replace(row,`${row}<div class="schedule-verification"><dd>Program verificat la <time datetime="2026-08-18">18 august 2026</time></dd></div>`)});return html.replace('<b>Informațiile despre program se pot modifica.</b><br>Dacă ai dubii, verifică programul înainte de deplasare.','<b>Informațiile despre program se pot modifica.</b><br>Toate centrele din țară sunt închise în zilele de sărbătoare națională.<br>Dacă ai dubii, verifică programul înainte de deplasare.')}
cityCentrePage=addCityScheduleVerification;
window.addEventListener('hashchange',route);window.addEventListener('popstate',route);route();
