// Usage: node verify-locales.cjs [local HTTP origin]
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require('playwright');const origin=process.argv[2]||'http://127.0.0.1:8765';
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage();let errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://**/*',r=>r.abort());
function files(dir){return fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.isDirectory()?files(path.join(dir,e.name)):e.name==='index.html'?[path.join(dir,e.name)]:[])}
for(const file of files(path.join(__dirname,'hu'))){const url='/'+path.relative(__dirname,file).replaceAll('\\','/').replace(/index.html$/,'');await page.goto(origin+url,{waitUntil:'domcontentloaded'});await page.waitForSelector('main h1,main h2');assert.equal(await page.locator('html').getAttribute('lang'),'hu');assert.equal(await page.locator('link[rel="canonical"]').getAttribute('href'),'https://doneazasange.ro'+url);assert.equal(await page.locator('link[hreflang="ro"]').count(),1);assert.equal(await page.locator('link[hreflang="hu"]').count(),1);const broken=await page.evaluate(()=>[...document.querySelectorAll('a[href]')].filter(a=>a.origin===location.origin&&/^\/(?:centre|cum-donez|intrebari-frecvente|contact)\//.test(a.pathname)).map(a=>a.href));assert.deepEqual(broken,[],url)}
await page.goto(origin+'/hu/intrebari-frecvente/?q=aszpirin');assert.equal(await page.locator('.faq-item').count(),1);assert.match(await page.locator('.faq-item').innerText(),/aszpirin/);await page.locator('#faq-search').fill('');await page.locator('.chip').filter({hasText:'Vizsgálatok és vércsoport'}).click();assert.ok(await page.locator('.faq-item').count()>=3);
await page.locator('[data-lang="ro"]').click();await page.waitForURL(origin+'/intrebari-frecvente/?q=aszpirin');assert.equal(await page.locator('html').getAttribute('lang'),'ro');await page.locator('[data-lang="hu"]').click();await page.waitForURL(origin+'/hu/intrebari-frecvente/?q=aszpirin');
await page.goto(origin+'/hu/intrebari-frecvente/');await page.locator('.faq-item>button').first().click();await page.locator('[data-donation-date]').fill('2026-09-01');await page.locator('[data-donation-centre]').fill('CTS Harghita');await page.locator('[data-donation-centre]').dispatchEvent('change');assert.match(await page.locator('[data-donation-result]').innerText(),/november/);
await page.locator('[data-faq-search="plasmafereze"]').click();assert.ok(await page.locator('.faq-item').count()<47);
await page.route('**/contact/send.php*',r=>r.fulfill({contentType:'application/json',body:JSON.stringify({question:'2 + 3'})}));await page.goto(origin+'/hu/contact/');await page.waitForFunction(()=>document.querySelector('#contact-submit').textContent==='Üzenet küldése');await page.locator('#reveal-phones').click();assert.equal(await page.locator('#reveal-phones').textContent(),'Elérhetőségek elrejtése');
for(const width of [390,1440]){await page.setViewportSize({width,height:900});await page.goto(origin+'/hu/');assert.ok(await page.locator('main h1').innerText().then(s=>s.includes('Adj vért')));if(width===390){await page.locator('.menu-toggle').click();assert.ok(await page.locator('[data-lang="hu"]').isVisible())}}
assert.deepEqual(errors,[]);await browser.close();console.log('PASS: 64 HU pages, language switching, FAQ search/categories, calculator, contact labels, mobile menu');})().catch(e=>{console.error(e);process.exit(1)});
